[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
cached = "0.54.0"
log = "0.4.22"
paste = "1.0.15"
rayon = "1.10.0"
regex = "1.11.1"
simple_logger = "5.0.0"
ureq = "2.10.1"
